multiclass.pdf: \
multiclass.tex \
intro.tex \
background.tex \
properties.tex \
algorithm.tex \
results.tex \
bib.bib
	pdflatex multiclass.tex
	bibtex multiclass.aux
	pdflatex multiclass.tex
	pdflatex multiclass.tex
